### PR TITLE
Refactor CI to allow for more modularized presubmit checks

### PR DESCRIPTION
**Pull request by l9i**

### CODE REVIEW

**Comment by pkern** [comment]
I think it'd be useful to populate the workflow name field, as otherwise it's shown as the filename in the check overview.

I also don't understand the Python matrix. We should not test Python 2 (discontinued). And the matrix check then requests 3.x, so all tests on all platforms are executed with 3.9 instead of the matrix version. A sane pick of versions should also reduce the amount of checks.

**Comment by l9i** [comment]
> I think it'd be useful to populate the workflow name field, as otherwise it's shown as the filename in the check overview.

Done. What convention would you prefer `${lang}-presubmit`, or `presubmit-${lang}`?

> I also don't understand the Python matrix. We should not test Python 2 (discontinued). And the matrix check then requests 3.x, so all tests on all platforms are executed with 3.9 instead of the matrix version. A sane pick of versions should also reduce the amount of checks.

Done. Any hints on what would be the sane choice of versions would be appreciated.

**Comment by pkern** [comment]
Not speaking against this change, but we will also need to address internal bug b/182772536 while we are at it as the Copybara GitHub check references presubmits by their name (and also wants an exhaustive list for some reason).

I guess alternatively we can discuss again making GitHub primary, which might resolve that particular concern. /cc @burgerdev

**Review by pkern — APPROVED** [review]
Maybe we can just try it and fix up our internal presubmits later. :>

LGTM.

**Comment by pkern** [comment]
Hm, the internal review tool uncovered some stray end of the line whitespace in some of the yaml files. Would you mind purging that?

**Comment by l9i** [comment]
> Hm, the internal review tool uncovered some stray end of the line whitespace in some of the yaml files. Would you mind purging that?

Sure. I've also added the yamllint workflow.

**Pull request merged**
